export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_WATCHID = 'UPDATE_WATCHID';
export const CLEAR_LOCATION_REDUCER = 'CLEAR_LOCATION_REDUCER';

export const NEARBY_ADD = 'NEARBY_ADD';
export const NEARBY_REMOVE = 'NEARBY_REMOVE';

export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';
