export const AUTH_FIELD_CHANGE = 'AUTH_FIELD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

export const FETCH_NEARBY_SUCCESS = 'FETCH_NEARBY_SUCCESS';
export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';

export const DROP_SET_REF = 'DROP_SET_REF';
export const DROP_UPDATE = 'DROP_UPDATE';
export const DROP_EDIT_CONTENT = 'DROP_EDIT_CONTENT';
export const DROP_ADD_CONTENT = 'DROP_ADD_CONTENT';
export const DROP_DELETE_CONTENT = 'DROP_REMOVE_CONTENT';
export const DROP_SAVE_SUCCESS = 'DROP_SAVE_SUCCESS';

export const CONTENT_FORM_ADD = 'CONTENT_FORM_ADD';
export const CONTENT_FORM_EDIT = 'CONTENT_FORM_EDIT';
export const CONTENT_FORM_CLOSE = 'CONTENT_FORM_CLOSE';

export const CONTENT_UPDATE = 'CONTENT_UPDATE';
