export const SET_GEOQUERY = 'SET_GEOQUERY';
export const LOCATION_UPDATE = 'LOCATION_UPDATE';

export const NEARBY_ADD = 'NEARBY_ADD';
export const NEARBY_REMOVE = 'NEARBY_REMOVE';

export const FETCH_LIBRARY_SUCCESS = 'FETCH_LIBRARY_SUCCESS';

export const DROP_RESET = 'DROP_RESET';
export const DROP_UPDATE = 'DROP_UPDATE';
export const DROP_EDIT_CONTENT = 'DROP_EDIT_CONTENT';
export const DROP_ADD_CONTENT = 'DROP_ADD_CONTENT';
export const DROP_DELETE_CONTENT = 'DROP_REMOVE_CONTENT';
export const DROP_SAVE_SUCCESS = 'DROP_SAVE_SUCCESS';

export const CONTENT_FORM_ADD = 'CONTENT_FORM_ADD';
export const CONTENT_FORM_EDIT = 'CONTENT_FORM_EDIT';
export const CONTENT_FORM_CLOSE = 'CONTENT_FORM_CLOSE';

export const CONTENT_UPDATE = 'CONTENT_UPDATE';

export const NOOP = 'NOOP';
